(function(g){var window=this;'use strict';var A5a=function(a){g.W.call(this,{F:"div",N:"ytp-inline-preview-ui"});this.Ze=!1;this.player=a;this.T(a,"onStateChange",this.ZK);this.T(a,"videodatachange",this.Dn);this.T(a,"onInlinePreviewModeChange",this.XZ);this.De=new g.Un(this.Zs,null,this);g.M(this,this.De)},I6=function(a){g.cO.call(this,a);
this.j=new A5a(this.player);g.M(this,this.j);this.j.hide();g.BN(this.player,this.j.element,4);a.isInline()&&(this.load(),g.io(a.getRootNode(),"ytp-inline-preview-mode",!0),this.player.V().K("web_rounded_containers")&&g.io(a.getRootNode(),"ytp-rounded-inline-preview",!0),this.player.V().K("web_inline_player_disable_scrubbing")&&g.io(a.getRootNode(),"ytp-inline-preview-mode-no-scrubbing",!0))};
g.v(A5a,g.W);g.k=A5a.prototype;
g.k.sI=function(){this.tooltip=new g.VR(this.player,this);g.M(this,this.tooltip);g.BN(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Ic=new g.XO(this.player);g.M(this,this.Ic);var a=["ytp-inline-preview-scrim"];this.player.V().K("web_inline_player_expand_to_watch")||a.push("ytp-inline-preview-scrim-clear");this.di=new g.W({F:"div",Ga:a});g.M(this,this.di);this.di.Ca(this.element);this.T(this.di.element,"click",this.CD);this.player.V().K("web_inline_player_expand_to_watch")&&(a=new g.M2(this.player,
this),g.M(this,a),a.Ca(this.di.element));this.ji=new g.HR(this.player,this);g.M(this,this.ji);this.ji.Ca(this.di.element);this.controls=new g.W({F:"div",N:"ytp-inline-preview-controls"});g.M(this,this.controls);this.controls.Ca(this.element);a=new g.qQ(this.player,this);g.M(this,a);a.Ca(this.controls.element);a=new g.FR(this.player,this);g.M(this,a);a.Ca(this.controls.element);this.Cc=new g.FQ(this.player,this);g.M(this,this.Cc);g.BN(this.player,this.Cc.element,4);this.T(this.player,"appresize",this.Ab);
this.T(this.player,"fullscreentoggled",this.Ab);this.Ab()};
g.k.show=function(){g.Vn(this.De);this.Ze||(this.sI(),this.Ze=!0);0!==this.player.getPlayerState()&&g.W.prototype.show.call(this);this.Cc.show()};
g.k.hide=function(){this.De.stop();g.W.prototype.hide.call(this);this.player.isInline()||this.Ze&&this.Cc.hide()};
g.k.ra=function(){g.W.prototype.ra.call(this)};
g.k.CD=function(a){a.target!==this.di.element||this.player.V().K("web_inline_player_expand_to_watch")||this.player.Pa("onExpandInlinePreview",a)};
g.k.XZ=function(){g.io(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.Xd=function(){this.Cc.hc();this.ji.hc()};
g.k.Zs=function(){this.Xd();g.Vn(this.De)};
g.k.Ab=function(){g.WQ(this.Cc,0,this.player.gb().getPlayerSize().width,!1);g.IQ(this.Cc)};
g.k.ZK=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.Dn=function(a,b){this.player.isInline()&&g.io(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.KL)};
g.k.wc=function(){return this.tooltip};
g.k.Vf=function(){return!1};
g.k.Hg=function(){return!1};
g.k.Ks=function(){return!1};
g.k.ek=function(){return!1};
g.k.tA=function(){};
g.k.Gp=function(){};
g.k.Ev=function(){};
g.k.Im=function(){return null};
g.k.Vy=function(){return null};
g.k.bk=function(){return new g.tl(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.xt=function(a,b,c,d,e){var f=d=0,h=0,l=g.Hl(a);if(b){c=g.co(b,"ytp-miniplayer-expand-watch-page-button");var m=g.co(b,"ytp-mute-button"),n=g.co(b,"ytp-subtitles-button"),p=g.Fl(b,this.element);b=g.Hl(b);d=p.y+40;c&&(h=8);if(n||m)h=p.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.gb().getPlayerSize().width;h=g.Eg(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.An=function(){};
g.k.al=function(){return!1};
g.k.uA=function(){};g.v(I6,g.cO);I6.prototype.Bj=function(){return!1};
I6.prototype.load=function(){this.player.hideControls();this.j.show()};
I6.prototype.unload=function(){this.player.showControls();this.j.hide()};g.bO("inline_preview",I6);})(_yt_player);
